### ISSUE TITLE
Error in running VILMA

### ISSUE THREAD

**Issue by weiw23** [jeffspence/vilma#2]
Hi! I'm really eager to play around with VILMA! Thanks for writing an interesting paper! 

I successfully installed VILMA following the README in python 3.10.2 and got errors in running VILMA. error messages: ```Error in `python': corrupted double-linked list: ```  and ```*** Error in `python': malloc(): smallbin double linked list corrupted:```

I thought it was a python compile issue. I update python to 3.10.6 in my laptop and followed the README again to install and test VILMA. I was able to install VILMA again but still got issues as follows in running test.py: 
```
python -m pytest vilma/tests/test.py
====================================================== test session starts =======================================================
platform darwin -- Python 3.10.6, pytest-7.1.3, pluggy-1.0.0
rootdir: /Users/username/project/PRS/vilma
collected 83 items                                                                                                               

vilma/tests/test.py ............................................Fatal Python error: Aborted
... ...
Abort trap: 6
```
and try to run example.sh
```
bash example.sh 
WARNING:root:0 out of 5 total variants are missing sumstats
WARNING:root:0 alleles have been flipped
WARNING:root:Missing LD info for 0 variants. They will be ignored during optimization.
WARNING:root:The alleles did not match for 0 variants. They were flipped
Python(92666,0x1103f0600) malloc: Incorrect checksum for freed object 0x7fb06e0429c0: probably modified after being freed.
Corrupt value: 0x1fffffffffffffff
Python(92666,0x1103f0600) malloc: *** set a breakpoint in malloc_error_break to debug
example.sh: line 46: 92666 Abort trap: 6
```

Looking forward to your suggestions.
Thanks a lot.

**Comment by jeffspence** [comment]
Thanks for the report!  

I was able to reproduce this by updating to the latest `numba` and `llvm` suggesting that it's a bug in one of those (I will file a report).  For now, please downgrade to `numba` version `0.55.2`, with

`pip install numba==0.55.2`

and let me know if you still get errors on running the unit tests.

**Comment by weiw23** [comment]
Thanks a lot. 
I can run the test.py with numba 0.55.2.
